services:
  postgres:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_db_user
    secrets:
      - POSTGRES_PASSWORD
    networks:
      - internal_network
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
      KC_DB_URL: jdbc:postgresql://postgres/keycloak_db
      KC_DB_USERNAME: keycloak_db_user
    volumes:
      - ./realm-config:/opt/keycloak/data/import
#      - keycloack_configuration:/opt/keycloak/data/import
    secrets:
      - KEYCLOAK_ADMIN_PASSWORD
      - KC_DB_PASSWORD
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start", "--import-realm"] # ["start-dev", "--http-port", "7080", "--https-port", "7443"]
    ports:
      - "7080:7080"
      - "7443:7443"
    networks:
      - internal_network
    depends_on:
      - postgres
secrets:
  KEYCLOAK_ADMIN_PASSWORD:
    environment: "KEYCLOAK_ADMIN_PASSWORD"
  POSTGRES_PASSWORD:
    environment: "POSTGRES_PASSWORD"
  KC_DB_PASSWORD:
    environment: "POSTGRES_PASSWORD"
networks:
  ingress_network:
    driver: bridge
volumes:
  postgres_data:
#    keycloack_configuration:
